/* Competitor-only pack — from flux-competitive-analysis.md. No Flux baseline. */
window.FLUX_CI = {
  prepared: "17 Sep 2026",
  nameTheyOwn: {
    "UP&RUN Advance": "Action-compound — Indian heat + zero-sugar salt sachets",
    "UP&RUN Salties": "Family / kids hydration halo",
    "Fast&Up Reload": "Gym shout — drop-fizz-drink habit",
    "Fast&Up Reload Salts+": "High-Na flanker under gym brand",
    "Liquid I.V. Multiplier": "Stick culture + HUL trust",
    "Liquid I.V. Sugar-Free": "Premium zero-sugar stick",
    "MB Fuel One Hydr8": "Gym shout — HealthKart price floor",
    "Unived Elite": "Race-grade endurance authenticity",
    "Flow Hydration": "Event hydration (messy formula story)",
    "Gatorade India": "Sports myth — impulse RTD",
    "Electral ORS": "Clinic ORS — chemist mental model"
  },
  matrix: [
    {
      brand: "UP&RUN Advance",
      format: "Powder sachet",
      formatKey: "powder",
      na: 1000, naDisplay: "1000",
      k: 200, kDisplay: "200",
      mg: 60, mgDisplay: "60",
      sugar: "0 g",
      price: 40, priceDisplay: "~₹40",
      claim: "Zero sugar; Indian heat; Equinox; WADA/NADA",
      threat: "Closest high-Na zero-sugar peer",
      threatRank: 1,
      owns: "Action-compound"
    },
    {
      brand: "UP&RUN Salties",
      format: "Powder sachet",
      formatKey: "powder",
      na: 300, naDisplay: "300",
      k: 120, kDisplay: "120",
      mg: 30, mgDisplay: "30",
      sugar: "0 g",
      price: 44.9, priceDisplay: "₹44.9",
      claim: "Kids 4–14; pediatrician study claim",
      threat: "Family wallet / brand halo",
      threatRank: 1,
      owns: "Kids / family"
    },
    {
      brand: "Fast&Up Reload",
      format: "Effervescent tab",
      formatKey: "tabs",
      na: 180, naDisplay: "180",
      k: 77, kDisplay: "77",
      mg: 20, mgDisplay: "20",
      sugar: "<1 g claimed",
      price: 12, priceDisplay: "~₹12",
      claim: "Informed Choice; 5 electrolytes; convenience",
      threat: "Habit + distribution scale",
      threatRank: 4,
      owns: "Gym shout"
    },
    {
      brand: "Fast&Up Reload Salts+",
      format: "Powder sachet",
      formatKey: "powder",
      na: 900, naDisplay: "~900 (secondary)",
      k: 200, kDisplay: "200 (sec.)",
      mg: null, mgDisplay: "UNKNOWN",
      sugar: "0 claimed",
      price: 21, priceDisplay: "~₹21",
      claim: "High-Na zero sugar flanker",
      threat: "Direct Na flanker under big brand",
      threatRank: 4,
      owns: "High-Na under Fast&Up"
    },
    {
      brand: "Liquid I.V. Multiplier",
      format: "Stick",
      formatKey: "rtd",
      na: 500, naDisplay: "~500 (global; India UNKNOWN)",
      k: 370, kDisplay: "~370 (global)",
      mg: null, mgDisplay: "UNKNOWN",
      sugar: "~11 g (global)",
      price: 96, priceDisplay: "~₹96",
      claim: "3× electrolytes vs sports drink; HUL",
      threat: "Brand trust + sugar-hydration narrative",
      threatRank: 5,
      owns: "Stick culture"
    },
    {
      brand: "Liquid I.V. Sugar-Free",
      format: "Stick",
      formatKey: "rtd",
      na: null, naDisplay: "UNKNOWN (India PDP)",
      k: null, kDisplay: "UNKNOWN",
      mg: null, mgDisplay: "UNKNOWN",
      sugar: "0 claimed",
      price: 122, priceDisplay: "~₹122",
      claim: "Zero sugar + amino acids",
      threat: "Premium zero-sugar stick",
      threatRank: 5,
      owns: "Premium SF stick"
    },
    {
      brand: "MB Fuel One Hydr8",
      format: "Effervescent tab",
      formatKey: "tabs",
      na: 222, naDisplay: "222",
      k: 81, kDisplay: "81",
      mg: 23, mgDisplay: "23",
      sugar: "No added sugar (sucralose)",
      price: 10.5, priceDisplay: "~₹10–11",
      claim: "Gym rehydration + BCAAs",
      threat: "Price / HK ecosystem",
      threatRank: 6,
      owns: "Gym shout"
    },
    {
      brand: "Unived Elite",
      format: "Tub powder",
      formatKey: "powder",
      na: 1000, naDisplay: "1000",
      k: null, kDisplay: "UNKNOWN",
      mg: null, mgDisplay: "UNKNOWN",
      sugar: "Functional sucrose; 62 kcal",
      price: 75, priceDisplay: "₹75 (8 srv) / ₹37.5 (16)",
      claim: "Race-grade Na + betaine + bicarb",
      threat: "Endurance authenticity",
      threatRank: 3,
      owns: "Race-grade"
    },
    {
      brand: "Flow Hydration",
      format: "Stick / sachet",
      formatKey: "powder",
      na: 1000, naDisplay: "1000 (API)",
      k: 200, kDisplay: "200 (API)",
      mg: 60, mgDisplay: "60 (API)",
      sugar: "API 0 g; homepage 6.9 g glucose",
      price: 50, priceDisplay: "₹40–50",
      claim: "Clean electrolytes; events",
      threat: "Near-clone Na/K/Mg; messaging chaos",
      threatRank: 2,
      owns: "Event hydration"
    },
    {
      brand: "Gatorade India",
      format: "RTD 500 ml",
      formatKey: "rtd",
      na: 237, naDisplay: "~225–250 (typical)",
      k: null, kDisplay: "UNKNOWN",
      mg: null, mgDisplay: "UNKNOWN",
      sugar: "~30 g/500 ml typical",
      price: 50, priceDisplay: "~₹50/bottle",
      claim: "Mass sports drink",
      threat: "Occasion / impulse",
      threatRank: 7,
      owns: "Sports myth"
    },
    {
      brand: "Electral ORS",
      format: "Powder sachet",
      formatKey: "rtd",
      na: 340, naDisplay: "~340 (calc)",
      k: 157, kDisplay: "~157 (calc)",
      mg: null, mgDisplay: "UNKNOWN",
      sugar: "Dextrose 2.7 g/sachet",
      price: 4.6, priceDisplay: "~₹4.6",
      claim: "WHO-style medical ORS",
      threat: "Clinic / chemist mental model",
      threatRank: 7,
      owns: "Clinic ORS"
    }
  ],
  naChart: [
    { label: "UP&RUN Advance", value: 1000, cls: "navy" },
    { label: "Flow (API)", value: 1000, cls: "navy" },
    { label: "Unived Elite", value: 1000, cls: "navy" },
    { label: "Fast&Up Salts+", value: 900, cls: "" },
    { label: "LIV Multiplier*", value: 500, cls: "gold" },
    { label: "Electral (calc)", value: 340, cls: "muted" },
    { label: "UP&RUN Salties", value: 300, cls: "muted" },
    { label: "Gatorade RTD*", value: 237, cls: "muted" },
    { label: "MB Hydr8", value: 222, cls: "muted" },
    { label: "Fast&Up Reload", value: 180, cls: "muted" }
  ],
  priceChart: [
    { label: "LIV Sugar-Free", value: 122, cls: "gold" },
    { label: "LIV Multiplier", value: 96, cls: "gold" },
    { label: "Unived (8 srv)", value: 75, cls: "" },
    { label: "Flow 10-pack", value: 50, cls: "" },
    { label: "Gatorade bottle", value: 50, cls: "muted" },
    { label: "UP&RUN Salties", value: 44.9, cls: "" },
    { label: "UP&RUN Advance", value: 40, cls: "navy" },
    { label: "Unived (16 srv)", value: 37.5, cls: "muted" },
    { label: "Fast&Up Salts+", value: 21, cls: "" },
    { label: "Fast&Up Reload", value: 12, cls: "muted" },
    { label: "MB Hydr8", value: 10.5, cls: "muted" },
    { label: "Electral", value: 4.6, cls: "muted" }
  ],
  scatter: [
    { brand: "UP&RUN Adv", na: 1000, sugar: 0, x: 0, cls: "" },
    { brand: "Flow API", na: 1000, sugar: 0, x: 0.3, cls: "" },
    { brand: "Salts+", na: 900, sugar: 0, x: 0.6, cls: "" },
    { brand: "Unived", na: 1000, sugar: 5, x: 5, cls: "sugar" },
    { brand: "LIV Mult*", na: 500, sugar: 11, x: 11, cls: "sugar" },
    { brand: "MB Hydr8", na: 222, sugar: 0.5, x: 0.5, cls: "low" },
    { brand: "Reload", na: 180, sugar: 1, x: 1, cls: "low" },
    { brand: "Electral", na: 340, sugar: 2.7, x: 2.7, cls: "low" }
  ],
  costPerMgNa: [
    { label: "Salts+ (₹21/900)", value: 0.0233, display: "₹0.023" },
    { label: "UP&RUN (₹40/1000)", value: 0.040, display: "₹0.040" },
    { label: "Flow (₹50/1000)", value: 0.050, display: "₹0.050" },
    { label: "Unived ₹75/1000", value: 0.075, display: "₹0.075" }
  ]
};
